### ISSUE TITLE
Check value of parameter entity of method search_by_name

### ISSUE THREAD

**Issue by leonarf** [wikirate/wikirate4py#1]
Hello, I'm new to the wikirate api, and I found it difficult to understand that to use the method 'search_by_name', I have to pass a class as 'entity' parameter, instead of simply a string.
I tried using api.search_by_name("Company", "Adidas") instead of api.search_by_name(wikirate4py.Company, "Adidas")
Could we accept String or make the method throw an exception if the parameter 'entity' is not valid? Or both? ^^.

Maybe I can propose a commit to do this change if you agree to make this change.
Bye and thank you.

**Comment by vasgat** [comment]
Thanks for your feedback. I see the issue here. I am contemplating a bit with the idea. Maybe, it will be more useful if instead of the change you suggest, we replace this method with 6 different ones named as follow: search_companies_by_name(name), search_metrics_by_name(name), search_topics_by_name(name), search_projects_by_name(name) etc.  

This way, we remove the burden from the user to give as input also the correct entity. What do you think?

**Comment by leonarf** [comment]
Reading the wikirate4py.readthedocs.io, there is only two method to search, one for sources, and the other for everything else. I didn't already use the one for source so I don't why it's different from other kind of object.
If the future of wikirate4py is to provide specific method with specific parameter for each kind of object, splitting search_by_name into 6 differents method is a good idea. But if all 6 methods have the same parameters, my point of view is that having only one method is easier to use because it's easier to document.

**Comment by vasgat** [comment]
For sources, the python client allows you to search for a source based on a given url, this can be useful to a user in case they want to add new sources on the platform using the API and make sure the source does not already exist. Additionally, on wikirate the sources names are produced automatically, the user can define a title though on sources which is different from a name. 

Let's then have the change on the search_by_name method as you suggested. You can propose a commit and I can review it later. 

Thanks for your time and feed back :)
