### ISSUE TITLE
Add sources by uploading file instead of giving an external URL

### ISSUE THREAD

**Issue by leonarf** [wikirate/wikirate4py#4]
I've done a previous work about big french companies and I have gathered annual report from them. I would like to add them as source to wikirate using the API, but the function 'add_source' takes an URL as argument, instead of a file, whereas using the wikirate website, it seems possible to add source by uploading a file.
I can help to add this feature, but I would need some help to know what wikirate's api entry point I must use to do so.
Feel free to invite me to your slack (leonard at lebasic dot com), I didn't succeed to login myself :-(

**Comment by vasgat** [comment]
Hello Leonard, 
Thanks for pointing out, we wanted to add this feature on the client too. I am working on it, I will try to push a new version by the end of today. I will let you know, as soon as, the feature is there. I sent you an invite to our Slack and on a group we have on google groups.

**Comment by vasgat** [comment]
Version 1.0.9 contains now that functionality. I am closing the issue. Thanks for the feedback.
